block_type: paragraph
concepts: []
excerpt: Just tell me what version you want next.
heading: '**✔ Produce the *interactive* periodic table (SVG with hover tooltips)**'
id: GEN9-9180
lines: 2363-2365
location: genesis-9/axiom-box-the-harmonic-periodic-table-theorem::9-conclusion-matter-as-a-δ-harmonic-phenomenon::produce-the-interactive-periodic-table-svg-with-hover-tooltips::b1
parent_heading: '**9\. Conclusion: Matter as a δ-Harmonic Phenomenon**'
source: genesis-9\AXIOM_BOX__The_-Harmonic_Periodic_Table_Theorem.md
