id: GEN15-3241
location: genesis-15/the-mass-curvature-projection-theorem::ⅲ-proof-from-the-functor-stack::1-φ-decomposes-curvature-at-time-t::b1
source: genesis-15\The_Mass__Curvature_Projection_Theorem_.md
lines: 2449-2461
heading: '**1\. Φ decomposes curvature at time t**'
parent_heading: '**Ⅲ. Proof From the Functor Stack**'
block_type: paragraph
excerpt: 'Φ(κ(t))=⨁nλn(t)IdΦn(t)\\Phi(\\kappa(t)) \= \\bigoplus\_n \\lambda\_n(t)\\mathrm{Id}\_{\\Phi\_n(t)}Φ(κ(t))=n⨁​λn​(t)IdΦn​(t)​
  Thus harmonic modes evolve: * new eigenvalues'
concepts:
- Φ
- λ
- κ
- CSOI-lobe
- Φn
aliases:
- Bk886pk
tags:
- definitive
- low-uncertainty
is_formal: false
axiom_count: 0
theorem_count: 0
conversational_score: 0.0
is_technical: true
concept_density: 11.363636363636363
has_contradictions: false
has_ambiguity: false
is_definitive: true
max_severity: 0.0
