id: GEN15-3217
location: genesis-15/the-mass-curvature-projection-theorem::ⅱ-proof-derived-from-the-functor-stack::step-1-φ-decomposes-κ-into-harmonic-eigenmodes::b1
source: genesis-15\The_Mass__Curvature_Projection_Theorem_.md
lines: 2145-2153
heading: '**Step 1: Φ decomposes κ into harmonic eigenmodes**'
parent_heading: '**Ⅱ. Proof (Derived from the Functor Stack)**'
block_type: paragraph
excerpt: Φ(κ)=⨁ℓλℓIdΦℓ\\Phi(\\kappa)=\\bigoplus\_{\\ell} \\lambda\_{\\ell}\\mathrm{Id}\_{\\Phi\_{\\ell}}Φ(κ)=ℓ⨁​λℓ​IdΦℓ​​
  Each λₗ is the amplitude of the δ-Harmonic Ladder. These form the primordial curvature
  ...
concepts:
- Φ
- λ
- κ
- δ-Harmonic
- δ
- Harmonic Ladder
aliases:
- Bk890pk
tags:
- definitive
- low-uncertainty
is_formal: false
axiom_count: 0
theorem_count: 0
conversational_score: 0.0
is_technical: true
concept_density: 15.789473684210526
has_contradictions: false
has_ambiguity: false
is_definitive: true
max_severity: 0.0
